Renaming the static Sdk class to OpenTelemetrySdk
open-telemetry/opentelemetry-dotnet pull request #2048
Opened 2021-05-13 18:51 UTC by greaterthanmost

## Changes

Renaming the static `Sdk` class to `OpenTelemetrySdk`.  Sdk is very generic and implementing this class it into your code hinders its readability if there are multiple SDK's being implemented.  Naming the class `Sdk` is vague and assumes future developers working on the code are familiar with this library.  Explicit naming helps future proof code as well as improve the engineering experience of your consumers.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

2021-05-13 18:59 UTC, cijothomas commented on src/OpenTelemetry/.publicApi/net452/PublicAPI.Shipped.txt
> +OpenTelemetry.OpenTelemetrySdk
We cannot break public API, as the library has released stable 1.0 version and breaking changes can only be added with a major version bump.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/VERSIONING.md

2021-05-13 18:59 UTC, cijothomas requested changes
We cannot make any breaking changes to public API in 1.* versions.

2021-05-13 19:02 UTC, reyang requested changes
It's too late, no breaking change.

2021-05-13 19:50 UTC, greaterthanmost commented
> We cannot make any breaking changes to public API in 1.* versions.

I like to think of it as a "forced cleanup" rather than a breaking change.  :wink:

That is a great callout though.  Give me a moment, I will update the PR.

2021-05-13 20:45 UTC, reyang commented
I have a different opinion, I think for folks who want to be explicit, they can always use `OpenTelemetry.Sdk.CreateTracerProviderBuilder`.

2021-05-13 21:17 UTC, greaterthanmost commented
> I have a different opinion, I think for folks who want to be explicit, they can always use `OpenTelemetry.Sdk.CreateTracerProviderBuilder`.

The problem with that approach is you are relying on a namespace.  By the class name being `Sdk` there is no indication of what the class' purpose is.  Also, Visual Studio and other refactoring tools will automatically remove the namespace from a class so your implementation will be back to just `Sdk`.

The other problem with that approach is there are multiple classes in this project that have names that end with Sdk such as `AttributeTelemetrySdk` and `TracerProviderBuilderSdk` so naming conventions are not being followed consistently.

I know this comes down to preference and opinions but in my professional experience, meaningful naming conventions that reveal a class' intention is crucial for a codebase to remain maintainable for engineers who inherit code they did not write.

2021-05-15 19:00 UTC, ejsmith commented
I definitely agree with this change and the name has bothered me as well, but it does appear to be too late to make it.

2021-05-15 22:16 UTC, greaterthanmost commented
> I definitely agree with this change and the name has bothered me as well, but it does appear to be too late to make it.

It's not a breaking change. The `Sdk` class is still available, it is just marked as obsolete and the new class with the proper name is available with the same functions. 
In the next major release the `Sdk` class can be removed completely and the change can be added to the release notes so consumers will be aware of the change when they upgrade to the latest version.

2022-02-05 03:17 UTC, closed without merging