Remove net452 from shims project (#2139)
open-telemetry/opentelemetry-dotnet pull request #2146
Opened 2021-07-16 20:33 UTC by joaopgrassi

Another project from #2138

* [x] `CHANGELOG.md` updated for non-trivial changes
* [x] Design discussion issue #
* [ ] Changes in public API reviewed

2021-07-16 20:40 UTC, reyang commented on src/OpenTelemetry.Shims.OpenTracing/CHANGELOG.md
> +  supported is .NET 4.6.1. ([2138](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2138))
```suggestion
  supported is .NET 4.6.1. ([#2138](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2138))
```

2021-07-16 20:40 UTC, reyang approved these changes
LGTM.

2021-07-16 22:15 UTC, cijothomas commented on src/OpenTelemetry.Shims.OpenTracing/OpenTelemetry.Shims.OpenTracing.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Please add net461 here.

2021-07-17 01:06 UTC, cijothomas requested changes
Please add net461 as there is no other netframework target here.

2021-07-17 09:29 UTC, joaopgrassi commented on src/OpenTelemetry.Shims.OpenTracing/OpenTelemetry.Shims.OpenTracing.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Done.

2021-07-17 09:55 UTC, joaopgrassi commented
I think I fixed the remaining the issues @cijothomas.

Just something I noticed: Is there a reason why the package `Microsoft.CodeAnalysis.PublicApiAnalyzers` is only added on Windows? I ran a build/test locally and didn't get any errors because I use Linux, but then I saw the CI failing..

In order to generate the public api files, I had to manually add the package and run `dotnet format -a warn`. Since all worked fine, I wonder if we can't just always add the package? Then people would not forgot to add like I did. It's the first time I use this, so just asking to understand it.

2021-07-17 16:40 UTC, cijothomas approved these changes

2021-07-17 16:41 UTC, merged

2021-07-17 16:41 UTC, cijothomas commented
> I think I fixed the remaining issues @cijothomas.
> 
> Just something I noticed: Is there a reason why the package `Microsoft.CodeAnalysis.PublicApiAnalyzers` is only added on Windows? I ran a build/test locally and didn't get any errors because I use Linux, but then I saw the CI failing..
> 
> In order to generate the public api files, I had to manually add the package and run `dotnet format -a warn`. Since all worked fine, I wonder if we can't just always add the package? Then people would not forget to add the api files like I did. It's the first time I use this, so just asking to understand it.

I don't recollect why... If you can make PR to do it in both win/linux, and if that makes its easy for linux based devs to catch issues easily, we can take it. Thanks!