chore: Remove changelog from PR template
open-telemetry/opentelemetry-dotnet pull request #2685
Opened 2021-11-25 13:50 UTC by tomkerkhove

## Changes

Remove changelog from PR template since this no longer exists.

2021-11-25 14:49 UTC, pellared requested changes
What do you mean by "it does not exist"?

See:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/5067549/143462168-e8732bbc-d49c-4f17-afcd-39e2d3aaea07.png">

2021-11-25 18:27 UTC, reyang requested changes
This is not correct.
There are many `CHANGELOG.md` files in the project - each package has its own.

2021-11-25 19:18 UTC, pellared commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] `src/OpenTelemetry/CHANGELOG.md` updated for non-trivial changes
```suggestion
* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes
```

2021-11-26 07:45 UTC, tomkerkhove commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] `src/OpenTelemetry/CHANGELOG.md` updated for non-trivial changes
Good suggestion, thanks!

2021-11-26 08:45 UTC, pellared approved these changes

2021-11-26 19:51 UTC, reyang approved these changes

2021-11-26 20:02 UTC, merged