Expose filter for SQL Instrumentation
open-telemetry/opentelemetry-dotnet pull request #3232
Opened 2022-04-26 20:31 UTC by akorade

Fixes #.

## Changes
1. Added new Filter option to SQL instrumentation for both .NET core and .NET framework.
2. Updated Unit test cases.
3. Updated Readme file

For significant contributions please make sure you have completed the following items:

* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

Creating a new pull request as the old one got stale. https://github.com/open-telemetry/opentelemetry-dotnet/pull/3131

2022-04-27 01:40 UTC, cijothomas commented
@akorade sorry to let the old PR go stale - if you want to ressurect a stale PR, simply comment on it, or message in slack, and one of the maintainers can "unstale" it
.

2022-04-27 20:32 UTC, akorade commented
> @akorade sorry to let the old PR go stale - if you want to ressurect a stale PR, simply comment on it, or message in slack, and one of the maintainers can "unstale" it .

No worries , I did not see an option to revive that PR so ended up creating a new one.

2022-05-06 16:18 UTC, cijothomas commented
@akorade Sorry for getting to this late (and also, I merged a minor test fix, which cause conflict :( )

While the overall idea is good, I'd suggest to:

Add Filter capability only for the .NET Core route. The `Enrich` option is also only available for .NET Core only. The reason is that, for .NET Framework, there is no need of providing Enrich/Filter by the SqlInstrumentation. The general purpose `ActivityProcessor` can be used for the same in .NET Framework. In case of .NET Core, Enrich/Filter by this instrumentation library is useful as it can give access to additional context (i.e the SQLCommand instance itself.)
(This is mentioned in the readme.md file as well)

Could you reduce the scope of this to just .NET Core?

2022-05-06 16:23 UTC, cijothomas commented on src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
> +                        _ = this.commandFetcher.TryFetch(payload, out var command);
I'd suggest to do this and Filter *after* the StartActivity() call. In typical case where user does not have filter, we want to first call StartActivity(), which will run samplers, and decide if this activity should even be collected. If not, we don't need to pay the cost of "fetching" command from payload. This PR alters the flow by always having to pay the cost of "fetching" command.

2022-05-06 16:24 UTC, cijothomas requested changes
Overall Good, blocking to address 2 comments:
1. Scope down to .NET Core only
2. Fetch command from payload after samplers are run, i.e after startactivity

2022-05-16 18:32 UTC, akorade commented
> Overall Good, blocking to address 2 comments:
> 
> 1. Scope down to .NET Core only
> 2. Fetch command from payload after samplers are run, i.e after startactivity

-> We want the filter to work for .NET Framework , is there any particular reason why we want it for .NET Core only?
-> If we do run Filter after starting activity it already will be sampled and exported. 
     To address this what if we call the Fetch method only if the filter is not null and if filter is null invoke Fetch after the activity is started?

2022-05-16 20:34 UTC, cijothomas commented
> -> We want the filter to work for .NET Framework , is there any particular reason why we want it for .NET Core only?

^ See this comment : https://github.com/open-telemetry/opentelemetry-dotnet/pull/3232#issuecomment-1119784595
Filter doesn't add any new value other than already provided by general OpenTelemetry extensibility points.

2022-05-16 20:43 UTC, cijothomas commented
> -> If we do run Filter after starting activity it already will be sampled and exported.
> To address this what if we call the Fetch method only if the filter is not null and if filter is null invoke Fetch after the activity is started?

We can stick with
1. Start Activity.
2. If activity is not null and isAllDataRequested=true, then only do anything else, including running the filter.

2022-06-01 03:54 UTC, closed without merging