OpenTelemetrySdkEventSource updates for activity tracking
open-telemetry/opentelemetry-dotnet pull request #5387
Opened 2024-02-23 23:02 UTC by pharring

## Changes

This change addresses issues with the OpenTelemetrySdkEventSource discovered during testing of profiler support for .NET applications. For example, we use dotnet-trace to profile an OpenTelemetry application. To enable activity tracking, we enable the OpenTelemetrySdkEventSource like this:

```
dotnet-trace collect --providers OpenTelemetry-Sdk 
```

In the resulting trace, however, we observe the following problem:
- ActivityIds are not set on the ActivityStarted/Stopped events from the OpenTelemetry-Sdk provider.

This is because of two problems:
1. The ActivityStarted/Stopped events are not emitted with the Start/Stop OpCodes.
2. Even when the OpCodes are added the ActivityTracker doesn't pair up the two events because they are using the wrong suffixes. The ActivityTracker specifically checks for the suffixes "Start" and "Stop". See item 4 here: https://learn.microsoft.com/dotnet/core/diagnostics/eventsource-instrumentation#best-practices and the code [here](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/ActivityTracker.cs,cc4a994235d93cb4).

To address these two issues: 
1. Renamed ActivityStarted/Stopped to ActivityStart/Stop
2. Added the OpCode definitions to the Event attributes.

This isn't a public API change, but it is an observable difference if you're already using an EventListener or profiler on an OpenTelemetry application.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [x] Unit tests added/updated
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [x] Changes in public API reviewed (if applicable)

2024-02-25 15:48 UTC, cijothomas commented
@pharring Can you elaborate on the end goals? The eventsource is purely an internal logging mechanism for the OTel SDK(and other components), and do you plan to rely on that for a particular scenario? If you want to rely on something to get notified on Activity start/stop, then the OTel way would be to [author an `ActivityProcessor`](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#processor). Alternately, you can achieve that with pure `ActivityListener` without any OTel dependency as well.

2024-02-26 17:16 UTC, pharring commented
Hi @cijothomas, the end goal is to be able to light up the "with Activities" views in PerfView when viewing a trace collected from an OpenTelemetry app using an EventPipe profiler like dotnet-trace, or an ETW profiler like PerfView or Visual Studio.

The OpenTelemetrySdkEventSource already emits ActivityStarted/ActivityStopped events at the right place with spanIDs. Unfortunately, because they are mis-named, they don't trigger ActivityTracking. ActivityTracking is what enables the "with Activities" views in PerfView.

It is possible to work around OpenTelemetrySdkEventSource's deficiency by using the DiagnosticSourceEventSource provider instead. It supports ActivitySource tracking. However, the events are verbose (they include all event attributes) if all you need are activity tracking and the spanIds -- this is the case for adding OpenTelemetry support for Application Insights Profiler.

Having had the weekend to think about this, we might be able to improve on this PR without breaking back-compat:
Introduce a new Keyword (there's currently none defined in OpenTelemetrySdkEventSource) specifically for activity tracking and emit _additional_ events (ActivityStart/Stop) under that Keyword (at Informational level). Profilers can then target just that new Keyword, set the level to Informational and they won't see the existing ActivityStarted/Stopped events.

2024-02-26 18:11 UTC, cijothomas commented
@pharring Thanks for the explanation. I am not that concerned about the back-compat issue, as there was no explicit guarantee about the shape of internal logs.

I am more concerned that you want to take a dependency on this particular naming style, but the SDK does not guarantee to maintain that either. Worst case, there is no guarantee that we won't move away completely from EventSource itself (like in favor of ILogger).

I believe this can be solved elsewhere. For example, dotnet-monitor tool is already able to listen to Metrics, without any OTel component involved. Maybe a similar approach could be used for traces as well, so there is no need of taking a undesired dependency on OTEL SDK internal behavior.

2024-02-26 18:57 UTC, pharring commented
> I am more concerned that you want to take a dependency on this particular naming style, but the SDK does not guarantee to maintain that either. 

You might have misunderstood. This isn't something I invented. ActivityTracking via the -Start/-Stop convention and OpCode.Start/Stop is built into the framework and documented. https://learn.microsoft.com/dotnet/core/diagnostics/eventsource-instrumentation#best-practices
Profiler viewers (PerfView, Visual Studio and Application Insights Profiler) use activity tracking (in conjunction with TPL's async causality tracing) to isolate samples (call-stacks) and other events from a single activity (request) and track it end-to-end even across Task (async/await) boundaries. 

> Worst case, there is no guarantee that we won't move away completely from EventSource itself (like in favor of ILogger).

That would be -- unfortunate. I'm glad you brought it up. There's a unit test in this PR. Is that sufficient to ensure the EventSource's survival? Since the EventSource behavior is not expressible in PublicAPI.Shipped.txt, perhaps I can add a scary comment in the unit test to discourage removal.

> I believe this can be solved elsewhere. For example, dotnet-monitor tool is already able to listen to Metrics, without any OTel component involved. Maybe a similar approach could be used for traces as well, so there is no need of taking a undesired dependency on OTEL SDK internal behavior.

It's sort of similar for dotnet-trace. You enable EventSources via EventPipe or ETW with keywords and levels. dotnet-trace works fine for OpenTelemetry apps if you're interested in is app-wide bottlenecks. The problem is if you want to do activity-based (request-based) profiling -- the kind where you look at the timeline of a single request. The viewer needs to collate events and callstacks by activity and, if the app isn't emitting accurate Activity IDs, then everything collapses to a single root activity.

2024-02-26 19:01 UTC, pharring commented
> undesired dependency on OTEL SDK internal behavior.

Wait, are you saying that OpenTelemetrySdkEventSource is _not_ for public consumption? If so, I can respect that. Would you support introducing a new EventSource that _is_ public? Perhaps one that only contains the new ActivityStart/Stop events from this PR? At the same time, perhaps we could rename it to "OpenTelemetry-Sdk-Internal" to make that clear.

2024-02-26 19:14 UTC, reyang requested changes
I don't feel this is the right direction https://github.com/open-telemetry/opentelemetry-dotnet/pull/5387#issuecomment-1965015980.

2024-02-26 21:32 UTC, closed without merging

2024-02-27 18:13 UTC, samsp-msft commented
@pharring why not make this request to the runtime itself? This could be baked into Activity, so you are not dependent on tracing being done with OTel.

2024-02-28 00:18 UTC, pharring commented
Thank you for the feedback and the suggestion. We'll use DiagnosticSourceEventSource (Microsoft-Diagnostics-DiagnosticSource) for activity tracking instead.